version: "3.1"

services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - printgo_network

  express-api:
    restart: on-failure
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
      PORT: 8000
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
    env_file:
      - .env
    networks:
      - printgo_network

volumes:
  postgres_data:

networks:
    printgo_network:
        driver: bridge
