version: "3.1"

services:
  api:
    container_name: printgo-user-service
    restart: on-failure
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
      PORT: 8000
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - printgo_network

volumes:
  printgo_database:

networks:
    printgo_network:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.enable_icc: "true"
