version: "3.1"

services:
  user-api:
    container_name: user-api
    restart: on-failure
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
      PORT: 8000
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - printgo_network

networks:
  printgo_network:
    external: true