version: "3.1"

services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  express-api:
    restart: on-failure
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres-db

volumes:
  postgres_data: