version: "3.1"

services:
  database:
    container_name: printgo-database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - printgo_database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - printgo_network

  api:
    container_name: printgo-user-service
    restart: on-failure
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
      PORT: 8000
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - printgo_network
    command: >
      bash -c '
        yarn db:generate
        yarn db:push
        yarn start
      '

volumes:
  printgo_database:

networks:
    printgo_network:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.enable_icc: "true"
