version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  express-app:
    image: node:18
    working_dir: /app
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["npm", "start"]

volumes:
  postgres_data: